#!/usr/bin/env php
<?php

use Rdh\LaravelFactoryConverter\Commands\ConvertCommand;
use Symfony\Component\Console\Application;

$possiblePaths = [
    __DIR__ . '/../../autoload.php',
    __DIR__ . '/../vendor/autoload.php',
    __DIR__ . '/vendor/autoload.php',
];

foreach ($possiblePaths as $possiblePath) {
    if (file_exists($possiblePath)) {
        $path = $possiblePath;

        break;
    }
}

if (! isset($path)) {
    throw new \Exception("Could not find 'autoload.php'");
}

require_once $path;

$application = new Application();
$application->add($command = new ConvertCommand());
$application->setDefaultCommand($command->getName());
$application->run();
