#!/usr/bin/env php
<?php

use Rdh\LaravelFactoryConverter\Commands\ConvertCommand;
use Symfony\Component\Console\Application;

require_once __DIR__ . '/vendor/autoload.php';

$application = new Application();
$application->add($command = new ConvertCommand());
$application->setDefaultCommand($command->getName());
$application->run();
